// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.javabootcamp.model;

import com.javabootcamp.model.Meeting;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Meeting_Roo_Configurable {
    
    declare @type: Meeting: @Configurable;
    
}
