// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.javabootcamp.model;

import com.javabootcamp.model.Attendee;
import com.javabootcamp.model.AttendeeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AttendeeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AttendeeDataOnDemand: @Component;
    
    private Random AttendeeDataOnDemand.rnd = new SecureRandom();
    
    private List<Attendee> AttendeeDataOnDemand.data;
    
    public Attendee AttendeeDataOnDemand.getNewTransientAttendee(int index) {
        Attendee obj = new Attendee();
        setEmail(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        return obj;
    }
    
    public void AttendeeDataOnDemand.setEmail(Attendee obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 30) {
            email = email.substring(0, 30);
        }
        obj.setEmail(email);
    }
    
    public void AttendeeDataOnDemand.setFirstName(Attendee obj, int index) {
        String firstName = "firstName_" + index;
        if (firstName.length() > 30) {
            firstName = firstName.substring(0, 30);
        }
        obj.setFirstName(firstName);
    }
    
    public void AttendeeDataOnDemand.setLastName(Attendee obj, int index) {
        String lastName = "lastName_" + index;
        if (lastName.length() > 30) {
            lastName = lastName.substring(0, 30);
        }
        obj.setLastName(lastName);
    }
    
    public Attendee AttendeeDataOnDemand.getSpecificAttendee(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Attendee obj = data.get(index);
        Long id = obj.getId();
        return Attendee.findAttendee(id);
    }
    
    public Attendee AttendeeDataOnDemand.getRandomAttendee() {
        init();
        Attendee obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Attendee.findAttendee(id);
    }
    
    public boolean AttendeeDataOnDemand.modifyAttendee(Attendee obj) {
        return false;
    }
    
    public void AttendeeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Attendee.findAttendeeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Attendee' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Attendee>();
        for (int i = 0; i < 10; i++) {
            Attendee obj = getNewTransientAttendee(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
