// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.javabootcamp.model;

import com.javabootcamp.model.Attendee;
import com.javabootcamp.model.AttendeeDataOnDemand;
import com.javabootcamp.model.AttendeeIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AttendeeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttendeeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttendeeIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AttendeeIntegrationTest: @Transactional;
    
    @Autowired
    AttendeeDataOnDemand AttendeeIntegrationTest.dod;
    
    @Test
    public void AttendeeIntegrationTest.testCountAttendees() {
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", dod.getRandomAttendee());
        long count = Attendee.countAttendees();
        Assert.assertTrue("Counter for 'Attendee' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttendeeIntegrationTest.testFindAttendee() {
        Attendee obj = dod.getRandomAttendee();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to provide an identifier", id);
        obj = Attendee.findAttendee(id);
        Assert.assertNotNull("Find method for 'Attendee' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Attendee' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AttendeeIntegrationTest.testFindAllAttendees() {
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", dod.getRandomAttendee());
        long count = Attendee.countAttendees();
        Assert.assertTrue("Too expensive to perform a find all test for 'Attendee', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Attendee> result = Attendee.findAllAttendees();
        Assert.assertNotNull("Find all method for 'Attendee' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Attendee' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttendeeIntegrationTest.testFindAttendeeEntries() {
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", dod.getRandomAttendee());
        long count = Attendee.countAttendees();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Attendee> result = Attendee.findAttendeeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Attendee' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Attendee' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttendeeIntegrationTest.testFlush() {
        Attendee obj = dod.getRandomAttendee();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to provide an identifier", id);
        obj = Attendee.findAttendee(id);
        Assert.assertNotNull("Find method for 'Attendee' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAttendee(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Attendee' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttendeeIntegrationTest.testMergeUpdate() {
        Attendee obj = dod.getRandomAttendee();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to provide an identifier", id);
        obj = Attendee.findAttendee(id);
        boolean modified =  dod.modifyAttendee(obj);
        Integer currentVersion = obj.getVersion();
        Attendee merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Attendee' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttendeeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", dod.getRandomAttendee());
        Attendee obj = dod.getNewTransientAttendee(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Attendee' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Attendee' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Attendee' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AttendeeIntegrationTest.testRemove() {
        Attendee obj = dod.getRandomAttendee();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attendee' failed to provide an identifier", id);
        obj = Attendee.findAttendee(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Attendee' with identifier '" + id + "'", Attendee.findAttendee(id));
    }
    
}
