// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.javabootcamp.model;

import com.javabootcamp.model.Meeting;
import com.javabootcamp.model.MeetingDataOnDemand;
import com.javabootcamp.model.RoomDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MeetingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MeetingDataOnDemand: @Component;
    
    private Random MeetingDataOnDemand.rnd = new SecureRandom();
    
    private List<Meeting> MeetingDataOnDemand.data;
    
    @Autowired
    RoomDataOnDemand MeetingDataOnDemand.roomDataOnDemand;
    
    public Meeting MeetingDataOnDemand.getNewTransientMeeting(int index) {
        Meeting obj = new Meeting();
        setEndDate(obj, index);
        setStartDate(obj, index);
        return obj;
    }
    
    public void MeetingDataOnDemand.setEndDate(Meeting obj, int index) {
        Date endDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setEndDate(endDate);
    }
    
    public void MeetingDataOnDemand.setStartDate(Meeting obj, int index) {
        Date startDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartDate(startDate);
    }
    
    public Meeting MeetingDataOnDemand.getSpecificMeeting(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Meeting obj = data.get(index);
        Long id = obj.getId();
        return Meeting.findMeeting(id);
    }
    
    public Meeting MeetingDataOnDemand.getRandomMeeting() {
        init();
        Meeting obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Meeting.findMeeting(id);
    }
    
    public boolean MeetingDataOnDemand.modifyMeeting(Meeting obj) {
        return false;
    }
    
    public void MeetingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Meeting.findMeetingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Meeting' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Meeting>();
        for (int i = 0; i < 10; i++) {
            Meeting obj = getNewTransientMeeting(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
