// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.javabootcamp.model;

import com.javabootcamp.model.Meeting;
import com.javabootcamp.model.MeetingDataOnDemand;
import com.javabootcamp.model.MeetingIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MeetingIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MeetingIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MeetingIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MeetingIntegrationTest: @Transactional;
    
    @Autowired
    MeetingDataOnDemand MeetingIntegrationTest.dod;
    
    @Test
    public void MeetingIntegrationTest.testCountMeetings() {
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", dod.getRandomMeeting());
        long count = Meeting.countMeetings();
        Assert.assertTrue("Counter for 'Meeting' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MeetingIntegrationTest.testFindMeeting() {
        Meeting obj = dod.getRandomMeeting();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to provide an identifier", id);
        obj = Meeting.findMeeting(id);
        Assert.assertNotNull("Find method for 'Meeting' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Meeting' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MeetingIntegrationTest.testFindAllMeetings() {
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", dod.getRandomMeeting());
        long count = Meeting.countMeetings();
        Assert.assertTrue("Too expensive to perform a find all test for 'Meeting', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Meeting> result = Meeting.findAllMeetings();
        Assert.assertNotNull("Find all method for 'Meeting' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Meeting' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MeetingIntegrationTest.testFindMeetingEntries() {
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", dod.getRandomMeeting());
        long count = Meeting.countMeetings();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Meeting> result = Meeting.findMeetingEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Meeting' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Meeting' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MeetingIntegrationTest.testFlush() {
        Meeting obj = dod.getRandomMeeting();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to provide an identifier", id);
        obj = Meeting.findMeeting(id);
        Assert.assertNotNull("Find method for 'Meeting' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMeeting(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Meeting' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MeetingIntegrationTest.testMergeUpdate() {
        Meeting obj = dod.getRandomMeeting();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to provide an identifier", id);
        obj = Meeting.findMeeting(id);
        boolean modified =  dod.modifyMeeting(obj);
        Integer currentVersion = obj.getVersion();
        Meeting merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Meeting' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MeetingIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", dod.getRandomMeeting());
        Meeting obj = dod.getNewTransientMeeting(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Meeting' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Meeting' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Meeting' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MeetingIntegrationTest.testRemove() {
        Meeting obj = dod.getRandomMeeting();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Meeting' failed to provide an identifier", id);
        obj = Meeting.findMeeting(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Meeting' with identifier '" + id + "'", Meeting.findMeeting(id));
    }
    
}
